@echo off
REM ****************************************************************************
<<<<<<< HEAD
REM Vivado (TM) v2020.2 (64-bit)
=======
REM Vivado (TM) v2020.1 (64-bit)
>>>>>>> 9f881404852e3b8f6847682d22899b1450dea088
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Thu Dec 03 03:58:22 +0900 2020
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
=======
REM Generated by Vivado on Wed Dec 02 05:32:14 +0900 2020
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
>>>>>>> 9f881404852e3b8f6847682d22899b1450dea088
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
REM compile VHDL design sources
=======
>>>>>>> 9f881404852e3b8f6847682d22899b1450dea088
echo "xvhdl --incr --relax -prj testBench_vhdl.prj"
call xvhdl  --incr --relax -prj testBench_vhdl.prj -log xvhdl.log
call type xvhdl.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
